README.md
- The FreeBSD Project is actually a downstream consumer.
- Direct users to the main repository on GitHub.
=> docs(`README`): minor fixes

net/wifibox-core/Makefile, net/wifibox-core/distinfo
- Drop `bhyve+` and FreeBSD 12 support
- Add support for definition of multiple PCI pass-through devices
=> chore: open `net/wifibox-core` 0.13.0

net/wifibox-alpine/Makefile, net/wifibox-alpine/distinfo
- Add bhyve-specific symlinks for Broadcom firmware files
- Fix unmounting `linprocfs` during build on FreeBSD 13 and later
=> chore(`net/wifibox-alpine`): Update to 20240106

net/wifibox-alpine/Makefile, net/wifibox-alpine/distinfo
- Update `linux-firwmare` to `20240115` to gain support for Intel BE200 (https://github.com/pgj/freebsd-wifibox/discussions/81)
=> chore(`net/wifibox-alpine`): Update to 20240116

net/wifibox/Makefile
Start preparing for releasing the next minor version of Wifibox.
=> chore(`net/wifibox`): bump to 1.4.0

README.md
The `sysutils/bhyve+` port is not used any longer.  Get rid of the related instructions to avoid confusions in the future and get ready for the removal of that port.
=> docs: remove outdated information about installing `bhyve+`

net/wifibox-core/Makefile, net/wifibox-core/distinfo
Update the `net/wifibox-core` to finalize the 0.13.0 release, see the [change log](https://github.com/pgj/freebsd-wifibox/releases/tag/0.13.0) for more information.
=> chore(`net/wifibox-core`): chase release of `0.13.0`

net/wifibox/Makefile
Prepare a new bug-fix release to address the background forking startup issue with `dhcpcd`.
=> chore(`net/wifibox`): bump to 1.4.1

net/wifibox-core/pkg-plist
There was a minor change recently to the version in the FreeBSD ports tree of the packaging list, which seems valid.  Import them to this tree to avoid reverting them later.
=> chore(`net/wifibox-core`): sync with the FreeBSD ports tree

README.md, net/wifibox-alpine/Makefile
It can cause problems if the path does not exist for `compat.linux.emul_path`.  Mention the possibility of this for the users, and implement checks around that to prevent this from happening.
=> fix(`net/wifibox-alpine`): check path of the run-time environment that Linuxulator uses

net/wifibox-alpine/Makefile, net/wifibox-alpine/distinfo
Import of https://github.com/pgj/freebsd-wifibox-alpine/pull/20.
=> fix(`net/wifibox-alpine`): remove APK metadata from the root file system

net/wifibox-alpine/Makefile
https://mirror.fel.cvut.cz/alpine/snapshots/ has become unavailable which was used as a source for getting Alpine Linux packages from a given point of time.  APK files are meant to be associated with a rolling package repository and as a consequence, they are moving targets.  This does not go well with our use case here.
It is not sure if this is going to be restored, that was probably served on a best-effort basis.
Switch to a more reliable solution and manually mirror the files to GitHub for each release.  Existing builds should just keep working, it makes difference only for new builds where optional APKs are used that were not cached by the FreeBSD distfile mirror.
Fixes [freebsd-wifibox#101](https://github.com/pgj/freebsd-wifibox/issues/101)
=> fix(`net/wifibox-alpine`): move away from the use of Alpine Linux mirrors

net/wifibox-core/Makefile, net/wifibox-core/distinfo
Relates to https://github.com/pgj/freebsd-wifibox/issues/104
=> chore(`net/wifibox-core`): Remove `nmdm(4)` device management

net/wifibox-core/Makefile, net/wifibox-core/distinfo
This PR is to bring the following changes:
- https://github.com/pgj/freebsd-wifibox/pull/107
- https://github.com/pgj/freebsd-wifibox/pull/110
- https://github.com/pgj/freebsd-wifibox/pull/114
- https://github.com/pgj/freebsd-wifibox/pull/115
- https://github.com/pgj/freebsd-wifibox/pull/117
=> chore(`net/wifibox-core`): chase recent updates

net/wifibox-core/Makefile
Make it more obvious that each of the options which unload vmm also stop the guest.
=> Make RECOVERY options more explicit.

net/wifibox-core/Makefile, net/wifibox-core/distinfo
This PR updates the port to hold the following changes:
- https://github.com/pgj/freebsd-wifibox/pull/124
- https://github.com/pgj/freebsd-wifibox/pull/125
=> chore(`net/wifibox-core`): Chase changes

net/wifibox-core/Makefile, net/wifibox-core/distinfo
Update `net/wifibox-core` to finalize the 0.14.0 release, see the [change log](https://github.com/pgj/freebsd-wifibox/releases/tag/0.14.0) for more information.
=> chore(`net/wifibox-core`): chase release of `0.14.0`

.github/workflows/checks.yml
Utilize GitHub actions to verify the contents of the repository. This is implemented through a test matrix of 13.4 and 14.1 releases where each of the ports are tested for fetch, checksum, build, package list, installation, and deinstallation issues.
=> chore(`workflows`): introduce CI support for build checks

.github/workflows/checks.yml
- FreeBSD 13.4 → [13.5](https://www.freebsd.org/releases/13.5R/) (released on March 11, 2025)
- FreeBSD 14.1 → [14.2](https://www.freebsd.org/releases/14.2R/) (released on December 3, 2024)
=> chore(`ci`): bump FreeBSD versions

net/wifibox-core/Makefile, net/wifibox-core/distinfo
- Consider built-in kernel modules on checking their presence ([freebsd-wifibox#136](https://github.com/pgj/freebsd-wifibox/issues/136))
=> chore(`net/wifibox-core`): open 0.15.0

net/wifibox-alpine/Makefile, net/wifibox-alpine/distinfo
The original kernel.org git web interface does not seem to be tolerating well when a ~600 MB snapshot file is pulled from there. Switch over to the kernel.org CDN and to the xz-compressed tarball to save some bandwidth and distribute the load.
=> fix(`net/wifibox-alpine`): optimize retrieval of `linux-firmware`

net/wifibox/Makefile
Tweak the package comment to make it say less ambitious.  Wifibox is not a device driver but an embedded router.  This way users may get less confused about what it could effectively deliver.
=> fix(`net/wifibox`): package comment line

net/wifibox-core/Makefile, net/wifibox-core/distinfo
Update `net/wifibox-core` to finalize the `0.15.0` release, see the [change log](https://github.com/pgj/freebsd-wifibox/releases/tag/0.15.0) for more information.
=> chore(`net/wifibox-core`): chase the release of `0.15.0`

net/wifibox-alpine/Makefile
Import the respective portion of the following sweeping change:
https://cgit.freebsd.org/ports/commit/?id=6e2da9672f79f44048d597f0f61e4646cdeade9d
=> chore(`net/wifibox-alpine`): sync with the FreeBSD ports tree

README.md, net/wifibox-alpine/Makefile, net/wifibox-alpine/pkg-plist
Users are not explicitly guided to understand the configuration options for the ports and some of the option names might appear "cryptic".  Improve the related experience by both mentioning the standard `config` target and changing the option names for the applications to reflect their purposes better.  Also, call out to the other repositories where each of the build options behind the respective port options are elaborated in details.
Fixes [freebsd-wifibox#155](https://github.com/pgj/freebsd-wifibox/issues/155)
=> docs: improve port configuration option description

net/wifibox-core/Makefile, net/wifibox-core/distinfo
- Improve wording about the mention of AMD-Vi on the manual page ([freebsd-wifibox#157](https://github.com/pgj/freebsd-wifibox/pull/157))
=> chore(`net/wifibox-core`): open 0.15.1

net/wifibox-core/Makefile, net/wifibox-core/distinfo
Update `net/wifibox-core` to finalize the `0.15.1` release, see the [change log](https://github.com/pgj/freebsd-wifibox/releases/tag/0.15.1) for more information.
=> chore(`net/wifibox-core`): chase the release of `0.15.1`
